[package]
name = "monitor"
version = "0.2.0"
authors = ["AUTHOR: Adrian Challinor "]
edition = "2018"

[dependencies]
clap = "2.32.0"
hostname = "0.1.5"
rocket = "0.4"
chrono =  "0.4"
uptime_lib = "0.1.0"
libc = "0.2.46"
systemstat = "0.1.3"
uname = "0.1.1"

